### ISSUE TITLE
Missing "email" field for author in package.json

### ISSUE THREAD

**Issue by nerdenough** [astrogif/astrogif#11]
Seems to be the cause of deb, rpm, and pacman builds for Linux failing.

![](http://media4.giphy.com/media/3uyIgVxP1qAjS/giphy.gif)

**Comment by jamesmacfie** [comment]
Pull down the latest now and give it a go. I added an `author` property in https://github.com/astrogif/astrogif/commit/2e0909dfe5c98b2813d6b8c09744482503666499

**Comment by nerdenough** [comment]
Ahhh, looks like there's [a second author tag](https://github.com/astrogif/astrogif/blob/master/package.json#L37-L40) at the bottom which the script is trying to use.

**Comment by jamesmacfie** [comment]
Huh, didn't see that there. Removed now

**Comment by nerdenough** [comment]
![](http://media2.giphy.com/media/ZDTW0zGJdZle0/giphy.gif)
