### ISSUE TITLE
Linux is not happy

### ISSUE THREAD

**Issue by srynot4sale** [astrogif/astrogif#25]
To run `npm run release-linux-deb` I needed to install some deps:

`sudo apt install graphicsmagick icnsutils`

Also, there are no linux releases being built any more :( Also it doesn't work on Linux. lololol I'll try fix

**Comment by jamesmacfie** [comment]
#yearoflinuxonthedesktop

**Comment by srynot4sale** [comment]
https://github.com/astrogif/astrogif/commit/9ecb8717adb27465d2edf6d04343abb7b1bdb3ec works..
https://github.com/astrogif/astrogif/commit/846ed39b00565f82b536a94a95e0373f5138052c fails.

So coincidentally, the same build that started breaking your tests on Travis, no longer works on Linux :penguin:
